### ISSUE TITLE
1.52.1.1.5 clarification

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#13]
**Section Number** [*Identify the most specific section number the issue occurs (e.g. 4.1.2)*](https://github.com/IHE/RAD.IMR/blob/Lynn-prepublication-edits/input/pagecontent/volume-1.md#152115-image-manager--image-archive)

**Issue** We say...
An Image Manager / Image Archive provides the images and related objects to the Report Readers.

An Image Manager / Image Archive is able to support DICOMweb WADO-RS Retrieve.

An Image Manager / Image Archive returns images in the requested rendered media type as defined in DICOM [PS3.18 Section 9.5](https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_9.5) "Retrieve Rendered Instance Transaction".

  Does this mean that the IMR Image / Manager shall support all  requirements for the Responder role in RAD-107?

I am confused by the last statement pointing to PS3.18 Sec 3.9.   Is that a separate requirement from RAD-107? (ie. that section is not referenced in RAD-107

**Proposed Change**  Clarify whether the IMR Img Mgr shall support "all" of RAD-107

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by kinsonho** [comment]
@lynnfel The support for rendered image in RAD-107 was added in CP-RAD-475. So it should be part of RAD-107 requirement, which is required by baseline DICOM.

**Comment by lynnfel** [comment]
So, for the purposes of IMR, a Report Reader really only needs to support the Get Rendered Instances request/response, but the IM (RAD-107 responder) must support all message pairs 

I agree that CP-475 language below clarifies the IM requirements.  
"A Requester shall support at least one of these request/response message pairs; a Responder shall support all four pairs, as defined in DICOM. "
