### ISSUE TITLE
Resolve TODO in Vol 1

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#14]
**Section Number** [*Identify the most specific section number the issue occurs (e.g. 4.1.2)*](https://github.com/IHE/RAD.IMR/blob/Lynn-prepublication-edits/input/pagecontent/volume-1.md#15241-concepts)

**Issue** There is still a TODO in that secton

**Proposed Change** If the whitepaper is not published when IMR Is ready for TI, you could keep this here with a suspected publication time frame if you think google could find it.  Otherwise move this to Open Issues as a 'to do' in a future release

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
@lynnfel I don't see a TODO in the Issue page. I do see a TODO in the test plan page https://profiles.ihe.net/RAD/IMR/testplan.html. Is this what you refer to?

**Comment by kinsonho** [comment]
Sorry I meant I didn't see a TODO in Vol 1.

**Comment by lynnfel** [comment]
I cannot find it either.   Will close the issue
