### ISSUE TITLE
very small typo in DiagnosticReport specification

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#17]
**Section Number** (https://profiles.ihe.net/RAD/IMR/StructureDefinition-imr-diagnosticreport.html)

**Issue** On the Differential Table for IMR Diagnostic report, I noticed a typo in the Description column for imagingStudy / presentedForm:pdf / contentType.     see proposed change below

**Proposed Change** change "applicatoin/pdf" to "application/pdf"

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by kinsonho** [comment]
Fixed and committed. It is now available in https://build.fhir.org/ig/IHE/RAD.IMR/StructureDefinition-imr-diagnosticreport.html.

Need to be published by Mary to make it available in profiles.ihe.net.
