### ISSUE TITLE
Reference to non-existing Note 2

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#19]
See https://profiles.ihe.net/RAD/IMR/RAD-141.html#2414141221-mapping-of-attributes-in-a-diagnostic-report

In Table 2:4.141.4.1.2.2.1-1, in the last row of the table, in Column 4, it says **"e.g., Findings and Impressions. See Note 2**"

However, there is no "Note 2" under this table.

I think the content for Note 2 is actually under Table 2:4.141.4.1.2.1-2.

**Comment by kinsonho** [comment]
@lynnfel I removed the 'See Note 2' in that row. It is already covered in the Table 2:4.141.4.1.2.1-2 as you pointed out.

See commit https://github.com/IHE/RAD.IMR/pull/21/commits/33c06191dfe62cf78c6e066a59eea963896d6823
