### ISSUE TITLE
Request from HL7 FHIR-i: tighten the context for the Associated Study Extension

### ISSUE THREAD

**Issue by bvdh** [IHE/RAD.IMR#20]
**Section Number** 
[IHE.RAD.IMR\IMR DiagnosticReport Associated Study - FHIR v4.0.1](https://profiles.ihe.net/RAD/IMR/StructureDefinition-associatedStudy.html)

**Issue** 
HL7 FHIR-i is reviewing extensions defined in the FHIR space in order to clean them up, remove redundant extensions and improve the definition of the remaining ones.
During this process, a set of IHE defined extensions where discussed that need work.
One of these extension is the "DiagnosticReport Associated Study" extension. The extension context is 'Element', allowing it to be used on any element on any resource. FHIR-i is concerned that this is far to generic and strongly recommends restricting the use to the specific context where it is intended to be used.

**Proposed Change** 
Restrict the use of these extensions to the root level of `DiagnosticReport`. This can be achieved by adding the line 
`Context: DiagnosticReport` to the header of these extensions in the sushi fsh file.

**Priority**:
- **Medium**: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by kinsonho** [comment]
@bvdh Thanks for the input.

The proposed change is accepted. Indeed a similar extension is also used in RAD.IRA profile and it has already been updated to restrict the context to DiagnosticReport.

We will do the same for RAD.IMR.

**Comment by lynnfel** [comment]
This github issue is now CP-RAD-528, assigned to Kinson, and will go through the regular IHE CP process.   This Github issue can be updated later according to that outcome.

**Comment by lynnfel** [comment]
Ready to publish
