### ISSUE TITLE
RAD-Y1 Capability Statement required?

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IMR#7]
**Section Number** RAD-Y1 2:4.Y1.4.3 https://build.fhir.org/ig/IHE/RAD.IMR/RAD-Y1.html#24y143-capabilitystatement-resource)

**Issue** In RAD-Y1 you say "Receiver shall provide a CapabilityStatement Resource as described in [ITI TF-2: Appendix Z.3](https://profiles.ihe.net/ITI/TF/Volume2/ch-Z.html#z.3-capabilitystatement-resource) indicating the resources associated with an IMR report has been implemented."
-- Isn't the receiver required to support all Resources that can be in a RAD-Y1 Bundle?
-- Isn't it the Sender who might use a CapabilityStatement to indicate that it only supports a subset of the RAD-Y1 requirements?

**Proposed Change** Require both Sender & Receiver to create a CapabilityStatement
For example, see MHD ITI-65: https://profiles.ihe.net/ITI/MHD/ITI-65.html#236543-capabilitystatement-resource

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by kinsonho** [comment]
That's correct. The CapabilityStatement section is a TODO in Y1 and Y3.

**Comment by lynnfel** [comment]
ok; I will close this issue
